/*
* This file was generated by a tool.
* Rerun "npm run models-from-database" to regenerate.
*/
export namespace Venel {
    export type Id = number;
    
    export interface AudioAttachment {
      'binaryContent'?: Buffer | null;
      'id'?: Id;
      'messageId'?: Id | null;
    }
    export interface BridgeInstance {
      'id'?: Id;
      'url': string;
    }
    export interface ChannelMember {
      'channelId': Id;
      'userId': Id;
    }
    export interface Channel {
      'bridged'?: boolean;
      'bridgedChannelId'?: Id | null;
      'bridgeInstanceId'?: Id | null;
      'id'?: Id;
      'name'?: string | null;
    }
    export interface ImageAttachment {
      'binaryContent'?: Buffer | null;
      'id'?: Id;
      'messageId'?: Id | null;
    }
    export interface MessageReaction {
      'messageId': Id;
      'reactionId': Id;
    }
    export interface Message {
      'channelId': Id;
      'createdAt'?: Date;
      'id'?: Id;
      'parentMessageId'?: Id | null;
      'senderId'?: Id | null;
      'text'?: string | null;
      'updatedAt'?: Date;
    }
    export interface Permission {
      'description'?: string;
      'id'?: Id;
      'name': string;
    }
    export interface Reaction {
      'content'?: string | null;
      'id'?: Id;
    }
    export interface RolePermission {
      'permissionId': Id;
      'roleId': number;
    }
    export interface Role {
      'description'?: string;
      'id'?: number;
      'name': string;
    }
    export interface UserRole {
      'roleId': number;
      'userId': Id;
    }
    export interface User {
      'createdAt'?: Date;
      'description'?: string | null;
      'displayname'?: string | null;
      'id'?: Id;
      'lastLoginIp'?: string | null;
      'passwordHash': string;
      'phoneNumber'?: string | null;
      'registrationIp'?: string | null;
      'updatedAt'?: Date;
      'username': string;
    }
}
