CREATE SCHEMA IF NOT EXISTS venel;

USE venel;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE,
  displayname VARCHAR(255),
  description TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  passwordHash CHAR(60)
);

CREATE TABLE IF NOT EXISTS hardwareKeys (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT,
  keyData VARBINARY(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  parentMessageId BIGINT,
  senderId BIGINT,
  text TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parentMessageId) REFERENCES messages (id),
  FOREIGN KEY (senderId) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS imageAttachments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  messageId BIGINT,
  binaryContent MEDIUMBLOB,
  FOREIGN KEY (messageId) REFERENCES messages (id)
);

CREATE TABLE IF NOT EXISTS audioAttachments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  messageId BIGINT,
  binaryContent MEDIUMBLOB,
  FOREIGN KEY (messageId) REFERENCES messages (id)
);

CREATE TABLE IF NOT EXISTS reactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS messageReactions (
  messageId BIGINT,
  reactionId BIGINT,
  PRIMARY KEY (messageId, reactionId),
  FOREIGN KEY (messageId) REFERENCES messages (id),
  FOREIGN KEY (reactionId) REFERENCES reactions (id)
);